[pytest]
testpaths = .
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -s -v --alluredir=./allure-results --html=./report/pytest_report.html --self-contained-html
markers =
    smoke: 冒烟用例
    p0: P0级核心用例
    p1: P1级重要用例
    p2: P2级一般用例
    login: 登录相关
    student: 学员管理
    enrollment: 报名缴费
    performance: 性能采样
    security: 安全测试
